apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.component }}
  labels:
    appName: {{ .Values.component }}
    projectName: {{ .Chart.Name }}
spec:
  {{ if .Values.initContainers.enabled }}
volumes:
  - name: vault
    emptyDir:
      sizeLimit: 5Mi
initContainers:
  - name: vault
    image: 838007018287.dkr.ecr.us-east-1.amazonaws.com/vault-init-container:v1
    env:
      - name: VAULT_ADDR
        value: "https://vault-internal.angadicnc.online:8200"
      - name: VAULT_TOKEN
        valueFrom:
          secretKeyRef:
            name: vault-token
            key: token
      - name: SECRET_NAME
        value: {{ .Chart.Name }}-dev/{{ .values.component }}
      - name: VAULT_SKIP_VERIFY
        value: "TRUE"
    volumeMounts:
      - mountPath: /data
        name: vault
  - name: schema
    image: 838007018287.dkr.ecr.us-east-1.amazonaws.com/schema-init-container:v1
    volumeMounts:
      - mountPath: /data
        name: vault
  {{ end }}
containers:
  - name: {{ .values.component }}
    image: 838007018287.dkr.ecr.us-east-1.amazonaws.com/{{ .Chart.Name }}-{{ .values.component }}:2.0.7
  {{ if .vales.initContainers.enabled }}
volumeMounts:
  - mountPath: /data
    name: vault
  {{ end }}